import random

mylist = ["ABCDEGH","BCDEFHI","ACDEFGI","ABDEFGH","BCEFGHI","ACDFGHI","ABDEGHI","ABCEFHI", "ABCDFGI","ABDFH","BCEGI","ACDFH","BDEGI", "ACEFH","BDFGI","ACEGH","ABDEGH","BCEFHI","ACDFGI","ADG","BEH","CFI","ABEG","BCFH","CDGI","ADEH","BEFI","ACFG","BDGH","CEHI","ADFI","ABCDFH","BCDEGI","ACDEFH","BDEFGI","ACEFGH","BDFGHI","ACEGHI","ABDFHI","ABCEGI","ABCEH","BCDFI","ACDEG","BDEFH","CEFGI","ADFGH","BEGHI","ACFHI","ABDGI", "ABCFGH","BCDGHI","ACDEHI","ABDEFI","ABCEFG","BCDFGH","CDEGHI","ADEFHI","ABEFGI","CEGI","ADFH","BEGI","ACFH","BDGI","ACEH","BDFI","ADEG","BEFH","CFGI","ADGH","BEHI","ACFI","ABDG","BCEH","CDFI","ADFG","BEGH","CFHI","ADGI","ABEH","BCFI","ACDG","BDEH","CEFI"]
random.shuffle(mylist)

print(mylist)